### ISSUE TITLE
How can user remove his submission?

### ISSUE THREAD

**Issue by Stroumph** [CaptainPatate/ascfpmfsrt#4]
If an user wished not submit a paper, how can remove his participation ?

**Comment by CaptainPatate** [comment]
I've been faster than you on this ;)
The commit a1208f06df85fdc66a9c953205f9593ddda65259 solves this issue.

**Comment by Stroumph** [comment]
Indeed.

An improvement may be an icon, such as a cross or a trash, after the submitter name used to remove an user to the submitter list.
